server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/huben?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
      mapper-locations: classpath:mapper/**/*.xml #注意：一定要对应mapper映射xml文件的所在路径


